<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQqd17xt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQqd17xt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQqd17xt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQqd17xt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQqd17xt\appProdProjectContainer(array(
    'container.build_hash' => 'Qqd17xt',
    'container.build_id' => '8e083ed0',
    'container.build_time' => 1540849893,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQqd17xt');
