<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSu4apyp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSu4apyp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSu4apyp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSu4apyp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSu4apyp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Su4apyp',
    'container.build_id' => '82f93d3e',
    'container.build_time' => 1541940294,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSu4apyp');
